name: taxi_booking
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  otp_text_field: ^1.1.3
  image_picker: ^1.0.7
  connectivity_plus: ^6.1.3
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  video_player: ^2.9.3
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.70.2
  get_storage: ^2.1.1
  country_code_picker: ^3.2.0
  lottie: ^3.2.0
  intl: ^0.20.2
  get: ^4.7.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/flag/
    - images/icons/
    - fonts/

  fonts:
    - family: Proxima Nova
      fonts:
        - asset: fonts/proximanova.otf
